# Generated by Django 4.0.6 on 2022-07-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('genero', models.IntegerField(choices=[(1, 'Hombre'), (2, 'Mujeres')])),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=30)),
                ('termino_condiciones', models.BooleanField(default=False)),
            ],
        ),
    ]
