# Generated by Django 4.0.5 on 2022-07-12 22:16

from django.db import migrations, models
import veranum_web.models


class Migration(migrations.Migration):

    dependencies = [
        ('veranum_web', '0002_habitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.CharField(default=veranum_web.models.random_id, editable=False, max_length=9, primary_key=True, serialize=False, null=False)),
                ('ida', models.CharField(max_length=30)),
                ('vuelta', models.CharField(max_length=30)),
                ('ninos', models.IntegerField(choices=[(1, '0'), (2, '1'), (3, '2'), (4, '3'), (5, '4'), (6, '5+')])),
                ('adultos', models.IntegerField(choices=[(1, '0'), (2, '1'), (3, '2'), (4, '3'), (5, '4'), (6, '5+')])),
                ('hotel', models.IntegerField(choices=[(1, 'Hotel Santiago'), (2, 'Hotel Valparaiso')])),
                ('piscina', models.BooleanField(default=False)),
                ('gimnasio', models.BooleanField(default=False)),
                ('spa', models.BooleanField(default=False)),
                ('cacha_tenis', models.BooleanField(default=False)),
            ],
        ),
    ]
